name: plant_system_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - wandb
    - transformers
    - streamlit
    - requests
    - tensorflow
    - pillow
    - opencv-python-headless
    - google.colab
    - streamlit-lottie
  - ipython
 
