name: plant_system_env
channels:
  - conda-forge
  - defaults
  - fastai
  
dependencies:
  - python=3.9
  - blinker=1.4
  - conda-forge:: grpcio
  - cachetools
  - conda-forge:: bokeh=2.4.2
  - conda-forge:: numpy=1.21.*
  - conda-forge:: nodejs=16.13.*
  - conda-forge:: flask
  - idna
  - protobuf
  - charset-normalizer
  - urllib3
  - conda-forge:: google-auth
  - conda-forge:: ipython
  - requests
  - pillow
  - pip
  - pip:
    - Flask-Testing
    - tensorflow==2.15.0
    - streamlit
    - streamlit-lottie
    - google-generativeai
    - opencv-python

 
