name: plant_system_env
channels:
  - conda-forge
  - defaults
  - fastai
  
dependencies:
  - python=3.9
  - blinker=1.4
  - grpcio
  - cachetools
  - bokeh=2.4.2
  - numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - idna
  - protobuf
  - charset-normalizer
  - urllib3
  - google-auth
  - ipython
  - requests
  - pillow
  - pip
  - pip:
    - Flask-Testing
    - tensorflow==2.15.0
    - streamlit
    - streamlit-lottie
    - google-generativeai
    - opencv-python

 
