name: plant_system_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - wandb
    - transformers
    - streamlit
    - requests
    - tensorflow
    - pillow
    - opencv-python
    - google.colab
    - cv2
  - ipython
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
