name: plant_system_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - blinker=1.4
  - cachetools
  - bokeh=2.4.2
  - numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - charset-normalizer
  - pip
  - pip:
    - Flask-Testing
    - tensorflow==2.15.0
    - streamlit
    - streamlit-lottie
    - google-generativeai

 
