name: plant_system_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - grpcio
  - blinker
  - cachetools
  - bokeh=2.4
  - numpy
  - nodejs
  - flask
  - protobuf
  - requests
  - pillow
  - ipython
  - google-auth
  - pip
  - pip:
    - streamlit
    - streamlit-lottie
    - tensorflow==2.15.0
    - google-generativeai
    - opencv-python
