name: plant_system_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - wandb
    - matplotlib
    - pandas
    - transformers
    - scipy
    - scikit-learn
    - streamlit
    - streamlit.cli
    - google-generativeai
    - streamlit-lottie
    - requests
    - tensorflow
    - pillow
    - numpy
    - opencv-python
    - ipython
    - textwrap
    - string
    - google.colab
    - cv2
