name: plant_system_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - wandb
    - torch==2.2.1+cu121
    - matplotlib
    - pandas
    - transformers
    - scipy
    - scikit-learn
    - streamlit
    - google-generativeai
    - streamlit-lottie
